# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
